version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: "tdd_nestjs_api_jest"
    restart: always
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    tty: true
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://mysh3ll:toor@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
      # Debugging port
      - 9229:9229
    networks:
      - dev

  postgres:
    image: postgres:13.3
    container_name: "tdd_nestjs_api_postgres"
    restart: always
    environment:
      POSTGRES_USER: mysh3ll
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db
    ports:
      - 35000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4:5.5
    container_name: "tdd_nestjs_api_pgadmin"
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: mysh3ll@admin.fr
      PGADMIN_DEFAULT_PASSWORD: toor
    ports:
      - 5050:80
    volumes:
      - my-data:/var/lib/pgadmin
    networks:
      - dev

networks:
  dev:

volumes:
  node_modules:
  pgdata:
  my-data:
